# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://elychess.club'
baseurl: ''
title: 'Ely Chess Club'
description: 'Ely Chess Club is an established Cambridgeshire chess club that plays in multiple local leagues.'
permalink: pretty
logo: "/images/noun-chess-knight-589743.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Fixtures
  url: https://ecflms.org.uk/lms/league/club/522/3117/org/fixtures
- title: Players
  url: https://www.ecfrating.org.uk/v2/new/list_players.php?club_code=9CAE

# Collections
collections:
  posts:
    title: News
    output: true
    description: "The latest club news"
    feature_text: |
      Learn what's happening at Ely Chess Club
    feature_image: "/images/mitchell-johnson-CZRNxAIYLzI-unsplash.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
